# Application
spring.application.name=pos-system

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/pos-system
spring.datasource.username=jobu
spring.datasource.password=Qwerty@1
spring.datasource.driver-class-name=org.postgresql.Driver



# spring.datasource.url=jdbc:postgresql://158.220.127.231:5432/pos-system
# spring.datasource.username=user
# spring.datasource.password=pass123
# spring.datasource.driver-class-name=org.postgresql.Driver



# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=pos_core
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Server
server.port=8080

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=password

rabbitmq.exchange.name=pos.exchange
rabbitmq.queue.email=pos.email.queue
rabbitmq.queue.sms=pos.sms.queue
rabbitmq.queue.notification=pos.notification.queue
rabbitmq.routing.email=pos.email.routing
rabbitmq.routing.sms=pos.sms.routing
rabbitmq.routing.notification=pos.notification.routing

# JWT
jwt.secret=dGhpcy1pcy1hLXZlcnktbG9uZy1zZWNyZXQta2V5LWZvci1qd3QtdG9rZW4tZ2VuZXJhdGlvbi1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# Mail Configuration (Zoho)
spring.mail.host=smtp.zoho.com
spring.mail.port=587
spring.mail.username=info@rentsafi.co.ke
spring.mail.password=m6FfJhqeqtyi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.zoho.com

# Email sender details
mail.from.email=info@rentsafi.co.ke
mail.from.name=POS Management System

# File Upload
file.upload-dir=uploads
file.base-url=http://localhost:8080/api/v1/public/files
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.filter=true
springdoc.show-actuator=false

# Account Security
security.max-failed-attempts=5
security.lock-duration-minutes=5
security.password-expiry-days=90
security.password-history-count=5

# Email Verification
security.email-verification-expiry-hours=24

# Password Reset
security.password-reset-expiry-minutes=60

# OTP
security.otp-expiry-minutes=5
security.otp-max-requests=3
security.otp-rate-limit-minutes=5
security.otp-max-wrong-attempts=5
